//
//  SpaceLibraryArticleModels.swift
//  spaceOfSpace
//
//  Created by Aleksandr Dergachev on 13.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SpaceLibraryArticleModel {
    // MARK: Use cases
    
    enum Article {
        struct Request {
            var articleTitle: String
        }
        
        struct Response {
            var article: SpaceLibraryArticle?
        }
        
        struct ViewModel {
            var displayedItems: SpaceLibraryArticle
        }
    }
}
