//
//  SpaceLibraryArticleWorker.swift
//  spaceOfSpace
//
//  Created by Aleksandr Dergachev on 13.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SpaceLibraryArticleWorker {
    let articlesManager = WikipediaAPIService()
    
    func fetch(articleTitle: String, success: @escaping (_ response: SpaceLibraryArticleModel.Article.Response) -> ()) {
        articlesManager.requestArticle(articleTitle: articleTitle) { article in
            guard article != nil else { return }
            success(SpaceLibraryArticleModel.Article.Response(article: article))
        }
    }
    
    func doSomeWork() {
    }
}
