//
//  SpaceLibraryTableOfContentsRouter.swift
//  spaceOfSpace
//
//  Created by Aleksandr Dergachev on 19.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SpaceLibraryTableOfContentsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SpaceLibraryTableOfContentsDataPassing
{
  var dataStore: SpaceLibraryTableOfContentsDataStore? { get }
}

class SpaceLibraryTableOfContentsRouter: NSObject, SpaceLibraryTableOfContentsRoutingLogic, SpaceLibraryTableOfContentsDataPassing
{
  weak var viewController: SpaceLibraryTableOfContentsViewController?
  var dataStore: SpaceLibraryTableOfContentsDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SpaceLibraryTableOfContentsViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SpaceLibraryTableOfContentsDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
