//
//  SpaceLibraryTableOfContentsPresenter.swift
//  spaceOfSpace
//
//  Created by Aleksandr Dergachev on 19.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SpaceLibraryTableOfContentsPresentationLogic {
    func presentTitles(sections: [SpaceLibraryArticleSection])
}

class SpaceLibraryTableOfContentsPresenter: SpaceLibraryTableOfContentsPresentationLogic {
    weak var viewController: SpaceLibraryTableOfContentsDisplayLogic?
    
    // MARK: Do something
    
    func presentTitles(sections: [SpaceLibraryArticleSection]) {
        viewController?.displayTitles(sections: sections)
    }
}
