//
//  SpaceLibraryTableOfContentsInteractor.swift
//  spaceOfSpace
//
//  Created by Aleksandr Dergachev on 19.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SpaceLibraryTableOfContentsBusinessLogic {
    var articleBusinessLogicDelegate: SpaceLibraryArticleBusinessLogic? { get set }
    func getArticle()
    func goToSection(sectionTitle: String)
}

protocol SpaceLibraryTableOfContentsDataStore {
    var article: SpaceLibraryArticle? { get set }
}

class SpaceLibraryTableOfContentsInteractor: SpaceLibraryTableOfContentsBusinessLogic, SpaceLibraryTableOfContentsDataStore {
    var presenter: SpaceLibraryTableOfContentsPresentationLogic?
    var worker: SpaceLibraryTableOfContentsWorker?
    var article: SpaceLibraryArticle?
    var articleBusinessLogicDelegate: SpaceLibraryArticleBusinessLogic?
    
    // MARK: Do something
    
    func getArticle() {
        presenter?.presentTitles(sections: article?.articleSections ?? [])
    }
    
    func goToSection(sectionTitle: String) {
        articleBusinessLogicDelegate?.goToSection(sectionTitle: sectionTitle)
    }
}
