import Foundation

struct SpaceObject{
    var radiusRatio:Float
    var orbitRatio:Float
    var orbitSpeed:Float
    var selfSpeed:Float
    var isSatellite:Bool
    var parent:String
    var diffuse:String
    var emission:String
    var normal:String
    var specular:String
    var notRounded:Bool
    var fileExtension:String
    var initScale: Float
}


var conf=[
    "Sun"    :SpaceObject(radiusRatio: 1,
                          orbitRatio: 1,
                          orbitSpeed: 0,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "Sun",
                          emission: "Sun",
                          normal:"",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Mercury":SpaceObject(radiusRatio: 0.3,
                          orbitRatio: 1.6,
                          orbitSpeed: 1,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "Mercury",
                          emission: "",
                          normal:"",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Venus"  :SpaceObject(radiusRatio: 0.34,
                          orbitRatio: 2.5,
                          orbitSpeed: 2,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "VenusD",
                          emission: "Venus",
                          normal:"",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Earth"  :SpaceObject(radiusRatio: 0.35,
                          orbitRatio: 3.8,
                          orbitSpeed: 2.3,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "EarthD",
                          emission: "EarthE",
                          normal:"EarthN",
                          specular: "EarthS",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Moon"   :SpaceObject(radiusRatio: 0.1,
                          orbitRatio: 0.5,
                          orbitSpeed: 20,
                          selfSpeed: 8,
                          isSatellite: true,
                          parent: "Earth",
                          diffuse: "Moon",
                          emission: "",
                          normal:"",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    "Mars"   :SpaceObject(radiusRatio: 0.32,
                          orbitRatio: 5.2,
                          orbitSpeed: 4.5,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "Mars",
                          emission: "",
                          normal:"",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Jupiter":SpaceObject(radiusRatio: 0.7,
                          orbitRatio: 7.2,
                          orbitSpeed: 15,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "Jupiter",
                          emission: "",
                          normal: "",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Saturn" :SpaceObject(radiusRatio: 0.65,
                          orbitRatio: 11.3,
                          orbitSpeed: 80,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "Saturn",
                          emission: "",
                          normal: "",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Uranus" :SpaceObject(radiusRatio: 0.5,
                          orbitRatio: 13.3,
                          orbitSpeed: 40,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "Uranus",
                          emission: "",
                          normal: "",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "Neptun" :SpaceObject(radiusRatio: 0.47,
                          orbitRatio: 15,
                          orbitSpeed: 80,
                          selfSpeed: 8,
                          isSatellite: false,
                          parent: "",
                          diffuse: "neptun",
                          emission: "",
                          normal: "",
                          specular: "",
                          notRounded: false,
                          fileExtension: "",
                          initScale:0),
    
    "rd-180"  :SpaceObject(radiusRatio: 1,
                           orbitRatio: 1,
                           orbitSpeed: 0,
                           selfSpeed: 8,
                           isSatellite: false,
                           parent: "",
                           diffuse: "rd-180",
                           emission: "",
                           normal:"3D Models.scnassets/engines",
                           specular: "",
                           notRounded: true,
                           fileExtension: "usdz",
                           initScale:876.5283),
    
    "falcon9"  :SpaceObject(radiusRatio: 1,
                           orbitRatio: 1,
                           orbitSpeed: 0,
                           selfSpeed: 8,
                           isSatellite: false,
                           parent: "",
                           diffuse: "falcon9",
                           emission: "",
                           normal:"3D Models.scnassets/rockets",
                           specular: "",
                           notRounded: true,
                           fileExtension: "usdz",
                           initScale:476.5283),
    
    "falcon1"  :SpaceObject(radiusRatio: 1,
                           orbitRatio: 1,
                           orbitSpeed: 0,
                           selfSpeed: 8,
                           isSatellite: false,
                           parent: "",
                           diffuse: "falcon1",
                           emission: "",
                           normal:"3D Models.scnassets/rockets",
                           specular: "",
                           notRounded: true,
                           fileExtension: "usdz",
                           initScale:476.5283),
    
    "falconHeavy"  :SpaceObject(radiusRatio: 1,
                           orbitRatio: 1,
                           orbitSpeed: 0,
                           selfSpeed: 8,
                           isSatellite: false,
                           parent: "",
                           diffuse: "falconHeavy",
                           emission: "",
                           normal:"3D Models.scnassets/rockets",
                           specular: "",
                           notRounded: true,
                           fileExtension: "usdz",
                           initScale:476.5283),
    
    "curiosity":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "curiosity",
                            emission: "",
                            normal:"3D Models.scnassets/staff",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "shuttle":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "shuttle",
                            emission: "",
                            normal:"3D Models.scnassets/rockets",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:1076.5283),
    
    "Saturn5":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "saturn5",
                            emission: "",
                            normal:"3D Models.scnassets/rockets",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "Soyuz-FG":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "Soyuz-FG",
                            emission: "",
                            normal:"3D Models.scnassets/rockets",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "Vostok-1":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "Vostok-1",
                            emission: "",
                            normal:"3D Models.scnassets/rockets",
                            specular: "",
                            notRounded: true,
                            fileExtension: "obj",
                            initScale:176.5283),//todo up
    
    "1D":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "1D",
                            emission: "",
                            normal:"3D Models.scnassets/engines",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "1DVacuum":SpaceObject(radiusRatio: 1,//todo down less
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "1DVacuum",
                            emission: "",
                            normal:"3D Models.scnassets/engines",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "be-4":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "be-4",
                            emission: "",
                            normal:"3D Models.scnassets/engines",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "F1":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "F1",
                            emission: "",
                            normal:"3D Models.scnassets/engines",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "Raptor":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "Raptor",
                            emission: "",
                            normal:"3D Models.scnassets/engines",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "RS-25":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "RS-25",
                            emission: "",
                            normal:"3D Models.scnassets/engines",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "TDJ2S":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "TDJ2S",
                            emission: "",
                            normal:"3D Models.scnassets/engines",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "apollo11":SpaceObject(radiusRatio: 1,//todo down
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "apollo11",
                            emission: "",
                            normal:"3D Models.scnassets/staff",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:676.5283),
    
    "helmet":SpaceObject(radiusRatio: 1,//todo up
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "helmet",
                            emission: "",
                            normal:"3D Models.scnassets/staff",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:276.5283),
    
    "iss":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "iss",
                            emission: "",
                            normal:"3D Models.scnassets/staff",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "perseverance":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "perseverance",
                            emission: "",
                            normal:"3D Models.scnassets/staff",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "vostok1":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "vostok1",
                            emission: "",
                            normal:"3D Models.scnassets/staff",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
    
    "voyager":SpaceObject(radiusRatio: 1,
                            orbitRatio: 1,
                            orbitSpeed: 0,
                            selfSpeed: 8,
                            isSatellite: false,
                            parent: "",
                            diffuse: "voyager",
                            emission: "",
                            normal:"3D Models.scnassets/staff",
                            specular: "",
                            notRounded: true,
                            fileExtension: "usdz",
                            initScale:476.5283),
]
