# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'


target 'spaceOfSpace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for spaceOfSpace

  pod 'FittedSheets'
  pod 'UIDrawer', :git => 'https://github.com/Que20/UIDrawer.git', :tag => '1.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Toaster'
  pod "SMScrollView"

end
